# Travis CI config.

language: php

# Use the new container-based infrastructure.
sudo: false

# Becasue PHP 7.0 isn't installed by default.
php:
  - 7.0

script:
  - phpenv global 5.2 && if find . -name '*.php' -exec php -l {} \; | grep '^Parse error'; then return 1; fi;
  - phpenv global 5.3 && if find . -name '*.php' -exec php -l {} \; | grep '^Parse error'; then return 1; fi;
  - phpenv global 5.4 && if find . -name '*.php' -exec php -l {} \; | grep '^Parse error'; then return 1; fi;
  - phpenv global 5.5 && if find . -name '*.php' -exec php -l {} \; | grep '^Parse error'; then return 1; fi;
  - phpenv global 5.6 && if find . -name '*.php' -exec php -l {} \; | grep '^Parse error'; then return 1; fi;
  - phpenv global 7.0 && if find . -name '*.php' -exec php -l {} \; | grep '^Parse error'; then return 1; fi;
  - phpenv global hhvm && if find . -name '*.php' -exec php -l {} \; | grep '^Parse error'; then return 1; fi;

# EOF
